import streamlit as st

def create_sidebar():
    with st.sidebar:
        st.image("https://graphlitplatform.blob.core.windows.net/samples/graphlit-logo-white-text.png")
        st.info("""
                ### ✅ Demo Instructions
                - **Step 1:** Browse for a picture to upload and be roasted.
                - **Step 2:** Read and listen to the roast of your uploaded picture. Image analysis uses [OpenAI GPT-4 Turbo 128k Vision](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo).  Audio generation done with [ElevenLabs](https://elevenlabs.io).
                """)

        st.warning("All roasts are purely for entertainment purposes, not an opinion by Graphlit, and are generated by an AI model. Uploaded pictures and published audio files are deleted periodically.")

        st.markdown("""
            [Learn more about Graphlit](https://www.graphlit.com)      
            [Support on Discord](https://discord.gg/ygFmfjy3Qx)            
            [API Reference](https://docs.graphlit.dev/graphlit-data-api/api-reference)     
            [Python SDK](https://pypi.org/project/graphlit-client/)     
            """)
